### ISSUE TITLE
杂 - YAML语法

### ISSUE THREAD

**Issue by Arweil** [Arweil/notes#60]
# YAML

[YAML TO JSON](https://www.convertjson.com/yaml-to-json.htm)

## 一、语法
* 大小写敏感
* 使用缩进表示层级关系
* 缩进不允许使用tab，只允许空格
* 缩进的空格数不重要，只要相同层级的元素左对齐
* '#' 表示注释

## 二、数据类型
* 对象
* 数组
* 纯量
  * 字符串
  * 布尔值
  * 整数
  * 浮点数
  * Null
  * 时间
  * 日期

### 1. 对象
对象键值对使用冒号结构表示<code>key: value</code>，冒号后面要加一个空格。

* 例子1：
  ```yaml
  key: 
    child-key: value
    child-key1: value1
  ```

  对应的JSON格式：
  ```json
  {
    "key": {
      "child-key": "value",
      "child-key1": "value1"
    }
  }
  ```

* 例子2：
  ```yaml
  key: { child-key: value, child-key1: value1 }
  ```

  对应的JSON格式：
  ```json
  {
    "key": {
      "child-key": "value",
      "child-key1": "value1"
    }
  }
  ```

### 2. 数组
以 <code>-</code> 开头的行表示构成一个数组

* 例子1：

  ```yaml
  - A
  - B
  - C
  ```

  对应的JSON格式：

  ```json
  [
    "A",
    "B",
    "C"
  ]
  ```

* 例子2：
  ```yaml
  key: [value1, value2]
  ```
  对应的JSON格式：
  ```json
  {
    "key": [
      "value1",
      "value2"
    ]
  }
  ```

* 例子3：
  ```yaml
  -
    - A
    - B
    - C
  ```
  对应的JSON格式：
  ```json
  [
    [
      "A",
      "B",
      "C"
    ]
  ]
  ```

* 例子4：
  ```yaml
  companies:
    -
      id: 1
      name: company1
      price: 200W
    -
      id: 2
      name: company2
      price: 500W
  ```

  使用流式表示
  ```yaml
  companies: [{id: 1,name: company1,price: 200W},{id: 2,name: company2,price: 500W}]
  ```
  他们对应的JSON格式：
  ```json
  {
    "companies": [
      {
        "id": 1,
        "name": "company1",
        "price": "200W"
      },
      {
        "id": 2,
        "name": "company2",
        "price": "500W"
      }
    ]
  }
  ```

### 3. 复合结构

```yaml
languages:
  - Ruby
  - Perl
  - Python 
websites:
  YAML: yaml.org 
  Ruby: ruby-lang.org 
  Python: python.org 
  Perl: use.perl.org
```
对应的JSON格式：
```json
{
  "languages": [
    "Ruby",
    "Perl",
    "Python"
  ],
  "websites": {
    "YAML": "yaml.org",
    "Ruby": "ruby-lang.org",
    "Python": "python.org",
    "Perl": "use.perl.org"
  }
}
```

## 三、引用
1. <code>&</code> 用来建立锚点
2. <code><<</code> 表示合并到当前的数据
3. <code>*</code> 用来引用锚点

* 例1：
  ```yaml
  defaults: &defaults
    adapter:  postgres
    host:     localhost

  development:
    database: myapp_development
    <<: *defaults

  test:
    database: myapp_test
    <<: *defaults
  ```

  相当于：
  ```yaml
  defaults:
    adapter:  postgres
    host:     localhost

  development:
    database: myapp_development
    adapter:  postgres
    host:     localhost

  test:
    database: myapp_test
    adapter:  postgres
    host:     localhost
  ```

  对应的JSON：
  ```json
  {
    "defaults": {
      "adapter": "ture",
      "host": "localhost"
    },
    "development": {
      "database": "myapp_development",
      "adapter": "ture",
      "host": "localhost"
    },
    "test": {
      "database": "myapp_test",
      "adapter": "ture",
      "host": "localhost"
    }
  }
  ```

* 例2：
  ```yaml
  - &showell Steve 
  - Clark 
  - Brian 
  - Oren 
  - *showell
  ```
  相当于：
  ```yaml
  - Steve 
  - Clark 
  - Brian 
  - Oren 
  - Steve
  ```
  对应的JSON：
  ```json
  [
    "Steve",
    "Clark",
    "Brian",
    "Oren",
    "Steve"
  ]
  ```
